### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by shannpersand** [typeatcooperbest/typeatcooperbest.github.io#2]
- [x] about page margins
- [x] add portraits
- [x] main home margins
- [x] scaling on typeface list
